steps:
  # Step 1: Ensure directories exist before running the script
  - name: "gcr.io/cloud-builders/bash"
    script: |
      mkdir -p dags data
      echo "✅ Created missing directories"

  # Step 2: Install Python dependencies
  - name: 'python'
    entrypoint: pip
    args: ["install", "-r", "utils/requirements.txt", "--user"]

  # Step 3: Run Python script to upload DAGs & Data to Composer
  - name: 'python'
    entrypoint: python
    args:
      - "utils/add_dags_to_composer.py"
      - "--dags_directory=${_DAGS_DIRECTORY}"
      - "--dags_bucket=${_DAGS_BUCKET}"
      - "--data_directory=${_DATA_DIRECTORY}"

  # Step 4: Fallback - Directly copy files using gsutil
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "cp", "-r", "dags/*", "gs://${_DAGS_BUCKET}/dags/"]

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "cp", "-r", "data/*", "gs://${_DAGS_BUCKET}/data/"]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DAGS_DIRECTORY: "dags/"
  _DAGS_BUCKET: "us-central1-demo-instance-224c07b2-bucket"
  _DATA_DIRECTORY: "data/"
